name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ] # আপনার main/master branch এর নাম লিখুন

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # IMPORTANT: '<your-repo-name>' এর জায়গায় আপনার repo-র নাম দিন
      - name: Build Web App
        run: flutter build web --release --base-href "/https://github.com/aritradev/Portfolio-Flutter/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4